---
- name: manage frcvision
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  tasks:
  - apt:
      name:
      - python3
      - python3-pip
      state: latest
      update_cache: yes
      cache_valid_time: 86400
  - name: copy files without backup
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      mode: 0644
      owner: root
      group: root
    with_items:
      - { src: 'ansible.cfg', dst: '/etc/ansible' }
